# Base-R


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(tidyverse)
library(datasauRus)
library(knitr)
library(nycflights13)
options("kableExtra.html.bsTable" = T)
kable_pretty <- function(data) {
  kable(data, "html") %>%
    kable_styling(bootstrap_options = c("striped", "condensed", full_width=T, position = "center"), full_width=F)
}
```


Little excursion into some essential base-r functions...

## Vectors

Define a vector

```{r}
a <- c(1,3,6,3)
b <- c("e-scoot", "bike", "walk", "bounce")

```

Access element from vector

```{r}
a[3]
b[2]
```


## Data frames

Access a column by name using `$` 

```{r}
head(mpg$hwy)
```

Access a column by column number

<div class="columns-2">
```{r}
# note the difference
head(mpg[[9]]) 


head(mpg[,9])
```
<div>

## Access..

.. a row by number

```{r}
mpg[2,]
```

.. an element

First element in brackets: row
Second element in brackets: column

```{r}
mpg[2,9]
```

## column names

```{r}
colnames(mpg)
```

rename 3rd column (but you also know how to do this in tidyverse)

```{r}
mpg2 <- mpg
colnames(mpg2)[3] <- "test"
head(mpg2)
```
