
## Factors


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(tidyverse)
library(datasauRus)
library(knitr)
library(nycflights13)
options("kableExtra.html.bsTable" = T)
kable_pretty <- function(data) {
  kable(data, "html") %>%
    kable_styling(bootstrap_options = c("striped", "condensed", full_width=T, position = "center"), full_width=F)
}
```


__What are factors?__

- Categorical variables that have a fixed and known set of possible values.

- Factors have an order. 

- Base-R functionality or `library(forcats)`


## Factors Example

```{r}
summary(iris)

class(iris$Species)
```

## Factors are ordered

```{r, out.width="50%"}
levels(iris$Species)

iris %>% 
  ggplot(aes(x = Species, y = Sepal.Length)) + geom_jitter()
```

## Factors are ordered

```{r, out.width = "45%"}
# change order of levels
iris$Species <- factor(iris$Species, levels = c("virginica", "versicolor", "setosa"))

levels(iris$Species)

iris %>% 
  ggplot(aes(x = Species, y = Sepal.Length)) + geom_jitter()
```



