project:
  type: website
  output-dir: docs

website:
  title: "R4Eco: Data management and analysis in environmental sciences"
  repo-url: https://github.com/johannesingrisch/R4Eco-course
  repo-actions: [issue]
  navbar:
    background: primary
    search: true

  sidebar:
    style: "docked"
    type: "dark"
    contents:
      - text: "Home"
        file: index.qmd
      - text: "Course introduction"
        file: Organisation.qmd
      - text: "Getting started with R"
        file: 01_Introduction.qmd
      - section: "Data visualisation"
        text: "Visualisation"
        file: 02_Visualisation.qmd
        contents: 
          - href: 02_Exercise.qmd
            text: "Exercise"
      - text: "Data Wrangling"
        file: 03_Wrangling.qmd
        contents:
          - href: 03_Exercise.qmd
            text: "Exercise"
      - text: "Reading data"
        file: 04_Reading.qmd
#      - section: "Data Manipulation"
#        contents: 
#          - href: 03_xxxx.qmd
#            text: "Tidy data"
#          - href: ....qmd
#            text: "Data wrangling"
#      - section: "Useful stuff"
#        contents: 
#          - href: ...
#            text: Dates & Times


  page-footer: "Copyright 2022, Johannes Ingrisch" 


format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-copy: true

