project:
  type: website

website:
  title: "R4Eco"
  navbar:
    background: primary
    search: true

  sidebar:
    style: "docked"
    type: "dark"
    contents:
      - text: "Home"
        file: index.qmd
      - section: "Introduction"
        contents:
          - href: Organisation.qmd
            text: Course organisation
          - href: 01_Introduction.qmd
            text: "Getting started with R"
      - section: "Vizualisation"
        contents:
          - href: 02_Visualisation.qmd
            text: "Data viz"
  page-footer: "Copyright 2022, Johannes Ingrisch" 


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

